### ISSUE TITLE
Problem with decorator

### ISSUE THREAD

**Issue by undingen** [vinzenz/libpypa#23]
Currently decorators with nested attribute accesses generate an assert inside pyston :-(
E.g:
```python 
class C(object):
    @a.b.c.setter
    def foo(self, value):
        pass
```

I took a brief look at it and think the problem is that ```dotted_name()``` has the ```attr->attribute =  trailing_name;``` and ```attr->value = name;``` assignment swapped around.
But after swapping them there is still a problem, it looks like the order of the nodes is wrong.
libpypa output:
```
- decorators: [                                
    [Attribute]
      - attribute:                                     
        [Name]
          - context: Load
          - dotted: False
          - id: a
      - context: Load
      - value:                                     
        [Attribute]
          - attribute:                                         
            [Name]
              - context: Load
              - dotted: False
              - id: b
          - context: Load
          - value:                                         
            [Attribute]
              - attribute:                                             
                [Name]
                  - context: Load
                  - dotted: False
                  - id: c
              - context: Load
              - value:                                             
                [Name]
                  - context: Load
                  - dotted: False
                  - id: setter
    ]
```
cpython:
```
- decorator_list: [
    [Attribute]
        - attr: setter
        - ctx: Load
        - value: 
        [Attribute]
            - attr: c
            - ctx: Load
            - value: 
            [Attribute]
                - attr: b
                - ctx: Load
                - value: 
                [Name]
                    - ctx: Load
                    - id: a
]
```
As I have no knowledge of libpypa internals I'm looking for hint how I can most easily generate the correct (aka. reversed) tree without breaking anything else (function get's called from several places I'm not sure if it has to get reversed for all of them?) :-D.
